@startuml
'https://plantuml.com/sequence-diagram

package domain {
    class Player
    class Game
    class Session
    class Email
    package errors {
    class ServicesError
    }
}

package services {
    Interface GameServiceInterface
    Interface PlayerServiceInterface
    Interface SessionServiceInterface
}

package storage {
    Interface GameStorageInterface
    Interface PlayerStorageInterface
    Interface SessionStorageInterface
}
package webApi {
    Interface GameHandler
    Interface PlayerHandler
    Interface SessionHandler
}

domain -> services
domain.errors -> services
domain -> storage
domain -> webApi

storage -> services

services -> webApi

@enduml