@startuml
'https://plantuml.com/sequence-diagram

Interface GameStorageInterface {
    + create()
    + read()
    + readBy()
    + update()
    + delete()
}

Interface PlayerStorageInterface {
    + create()
    + read()
    + readBy()
    + update()
    + delete()
}

Interface SessionStorageInterface {
    + createSession()
    + readSession()
    + readSessions()
    + updateAddPlayer()
    + updateCapacityOrDate()
    + updateRemovePlayer()
    + deleteSession()
}

class GameStorage {
    + create()
    + read()
    + readBy()
    + update()
    + delete()
    - dataSource
}

class PlayerStorage {
    + create()
    + read()
    + readBy()
    + update()
    + delete()
    - dataSource
}

class SessionStorage {
    + createSession()
    + readSession()
    + readSessions()
    + updateAddPlayer()
    + updateCapacityOrDate()
    + updateRemovePlayer()
    + deleteSession()
    - dataSource
}

GameStorageInterface <|-- GameStorage
PlayerStorageInterface <|-- PlayerStorage
SessionStorageInterface <|-- SessionStorage

@enduml